My_First_Project/First_App/urls.py
from django.conf.urls import url
from django.urls import path
from First_App import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('musician_details/<pk>/', views.MusicianDetail.as_view(), name='musician_details'),
    path('add_musician/', views.AddMusician.as_view(), name='add_musician'),
    path('musician_update/<pk>/', views.UpdateMusician.as_view(), name='musician_update'),
    path('musician_delete/<pk>/', views.DeleteMusician.as_view(), name='musician_delete'),
]




My_First_Project/My_First_Project/urls.py

from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include(('First_App.urls','first_app'),namespace='first_app')),
]

My_First_Project/First_App/models.py
from platform import release
from django.db import models
from django.urls import reverse

# Create your models here.
class Musicians(models.Model):
    #id = models.AutoField(Primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name =models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name+" "+self.last_name+" played "+self.instrument+""

    def get_absolute_url(self):
        return reverse('first_app:musician_details', kwargs={'pk':self.pk})
    

class Album(models.Model):
    #id = models.AutoField(Primary_key=True) if we use CASCADE
    artist = models.ForeignKey(Musicians, on_delete=models.CASCADE, related_name='album_list')
    name =models.CharField(max_length=100)
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Best"),
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name+" got "+str(self.num_stars)+" stars "

My_First_Project/First_App/forms.py
from django import forms
from django.core import validators
#from First_App.models import Album, Musicians
from First_App import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musicians
        fields ='__all__'

class AlbumForm(forms.ModelForm):
    release_date= forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields ='__all__'


My_First_Project/First_App/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView,ListView,DetailView,CreateView,UpdateView, DeleteView
from First_App import models
from django.urls import reverse_lazy

# Create your views here.
class IndexView(ListView):
    context_object_name='musician_list'
    model = models.Musicians
    template_name = 'first_app/index.html'

class MusicianDetail(DetailView):
    context_object_name='musician'
    model = models.Musicians
    template_name = 'first_app/musician_details.html'

class AddMusician(CreateView):
    fields = ('first_name','last_name','instrument')
    model = models.Musicians
    template_name = 'first_app/musician_form.html'

class UpdateMusician(UpdateView):
    fields = ('first_name','last_name','instrument')
    model = models.Musicians
    template_name = 'first_app/musician_form.html'

class DeleteMusician(DeleteView):
    context_object_name='musician'
    model = models.Musicians
    success_url = reverse_lazy("first_app:index")
    template_name = 'first_app/delete_musician.html'

My_First_Project/First_App/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <title>{{ title }}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item active" style="padding-left: 50px">
                    <a class="nav-link" href="{%url 'first_app:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'first_app:add_musician' %}">Add Musician</a>
                </li>
            
            </ul>
        </nav>
    <div class="container" style='padding-top: 20px'>
        {% block body_block %}
        {% endblock %}
    </div>
    </body>
</html>

My_First_Project/First_App/templates/first_app/delete_musician.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<p>Delete {{musician.first_name}} {{musician.last_name}}</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" name="submit" value="Delete" class="btn btn-danger btn-sm">
    <a href="{% url 'first_app:musician_details' pk=musician.pk%}" class="btn btn-danger btn-sm">Cancel</a>
</form>
{% endblock %}

My_First_Project/First_App/templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
{% for musician in musician_list %}
<ul>
<li><a href="{%url 'first_app:musician_details' pk=musician.pk %}">
    {{musician.first_name}}  {{musician.last_name}}</a></li>
</ul>
{% endfor %}
{% endblock %}

My_First_Project/First_App/templates/first_app/musician_details.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body_block %}
<h3>Musician Details:</h3>
<p>{{musician.first_name}} {{musician.last_name}}</p>
<p>{{musician.instrument}}</p>
<ul>
<h3>Album:</h3>
{% for album in musician.album_list.all %}
    <li>{{album.name}}</li>
{% endfor %}
</ul>
<a href="{% url 'first_app:musician_update' pk=musician.pk %}" class="btn btn-warning btn-sm">Update</a>
<a href="{% url 'first_app:musician_delete' pk=musician.pk %}" class="btn btn-warning btn-sm">Delete</a>
{% endblock %}

My_First_Project/First_App/templates/first_app/musician_form.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body_block %}
{% if form.instance.pk %}
<h3>Update Musician</h3>
{% else %}
<h3>Musician Form:</h3>
{% endif %}
    <form method="POST">
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" name="submit" value="Add" class="btn btn-primary ">
    </form>
{% endblock %}

My_First_Project/templates/first_app/album_form.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h3>Album Form:</h3>
<form method="POST">
    {{ album_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add" class="btn btn-primary ">
</form>
{% endblock %}

My_First_Project/templates/first_app/album_list.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
    
    <h4>Artist Name: {{artist_info.first_name}} {{artist_info.last_name}} </h4>
    <h4> Instrument: {{ artist_info.instrument}} </h4>
    <h4>Artist Rating: {{ artist_rating.num_stars__avg}}</h4>
    <a href="{% url 'first_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-success btn-sm">Edit</a>
    <h4>List of Album</h4>
    <table class="table table-bordered">
        <tr>
            <th>Album Name</th>
            <th>Release Date</th>
            <th>Rating</th>
        </tr>

        {% for album in album_list %}
        <tr>
            <td><a href="{% url 'first_app:edit_album' album_id=album.id %}">{{ album.name }}</a></td>
            <td>{{ album.release_date|date:"M d,Y"}}</td>
            <td>{{ album.num_stars}}</td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{% url 'first_app:delete_artist' artist_id=artist_info.id %}" 
    class="btn btn-danger btn-sm" onclick="return confirm('Delete Musician?')">Delete</a>
{% endblock %}

My_First_Project/templates/first_app/delete.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<div class='alert alert-success'>{{delete_success}}</div>
{% endblock %}

My_First_Project/templates/first_app/edit_album.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h4>Edit Album: </h4>
{% if success_text %}
<div class='alert alert-success'>{{success_text}}</div>
{% endif%}
<form method="POST">
    {{ edit_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm ">
</form>
<br>
<a href="{% url 'first_app:delete_album' album_id=album_id %}" 
class="btn btn-danger btn-sm" onclick="return confirm('Delete this Album?')">Delete</a>
{% endblock %}

My_First_Project/templates/first_app/edit_artist.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h4>Edit Artist: </h4>
<form method="POST">
    {{ edit_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm ">
</form>
{% endblock %}